version: 2
updates:
  # Monitor Docker base images
  - package-ecosystem: "docker"
    directory: "/docker-socket-proxy"
    schedule:
      interval: "weekly"
      day: "monday"
      time: "04:00"
    commit-message:
      prefix: "chore(deps): "
      include: "scope"
    labels:
      - "dependencies"
      - "docker"
    reviewers:
      - "mattjacobson6"
