---
name: pgAdmin4
version: "1.0.32"
slug: pgadmin4
description: A PostgreSQL Management and Query tool
url: https://github.com/mattjacobson6/ha-addons/tree/main/pgadmin4

arch:
  - aarch64
  - amd64
  - i386
  - armv7

ingress: true
panel_icon: mdi:database
panel_title: pgAdmin4

hassio_api: true
auth_api: true
init: false
homeassistant: "0.92.0"
timeout: 20

map:
  - ssl:rw
  - share:rw
  - data:rw

options:
  system_packages: []
  init_commands: []
  leave_front_door_open: false

schema:
  system_packages:
    - str
  init_commands:
    - str
  leave_front_door_open: bool?
