name: cAdvisor
version: "1.0.3"
slug: cadvisor
description: Analyzes resource usage and performance characteristics of running containers
url: https://github.com/mattjacobson6/ha-addons/tree/main/cadvisor

init: false
startup: services
boot: auto

arch:
  - amd64

ports:
  8080/tcp: 8080
ports_description:
  8080/tcp: Metrics endpoint and web UI

webui: http://[HOST]:[PORT:8080]/
docker_api: true
full_access: true
host_ipc: true
host_dbus: true

watchdog: http://[HOST]:[PORT:8080]/healthz

privileged:
  - BPF
  - DAC_READ_SEARCH
  - IPC_LOCK
  - NET_ADMIN
  - NET_RAW
  - PERFMON
  - SYS_ADMIN
  - SYS_MODULE
  - SYS_NICE
  - SYS_PTRACE
  - SYS_RAWIO
  - SYS_RESOURCE
  - SYS_TIME

options:
  custom_args: ""

schema:
  custom_args: "str?"
