name: cAdvisor
description: Google's cAdvisor for container performance monitoring
version: "1.0.2"
slug: cadvisor
url: https://github.com/mattjacobson6/ha-addons/tree/main/cadvisor

init: false
startup: services
boot: auto

arch:
  - amd64

ports:
  8080/tcp: 8080

privileged: true
host_network: true
host_pid: true
apparmor: false
