daemon off;
worker_processes 1;
error_log /proc/1/fd/1;

events {
    worker_connections 512;
}

http {
    include         mime.types;
    default_type    application/octet-stream;

    access_log /proc/1/fd/1;

    pcre_jit        on;
    server_tokens   off;

    tcp_nodelay     on;
    tcp_nopush      on;
    sendfile        on;

    keepalive_timeout 65;
    client_max_body_size 4g;

    gzip on;

    map $http_upgrade $connection_upgrade {
        default upgrade;
        ''      close;
    }

    env SUPERVISOR_TOKEN;
    env DISABLE_HA_AUTHENTICATION;

    include /etc/nginx/includes/*.conf;
    include /etc/nginx/servers/*.conf;
}
